# Generated by Django 4.2.7 on 2023-12-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_friends_remove_user_friends_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
