# Generated by Django 4.2.7 on 2023-12-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_trend_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='PostAttachment',
        ),
    ]
